//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTask
    {
        public string ID { get; set; }
        public string Task { get; set; }
        public int Priority { get; set; }
        public string User_ID { get; set; }
        public bool Done { get; set; }
        public System.DateTime WasCreated { get; set; }
    
        public virtual User User { get; set; }
    }
}
